openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: ZEGO Support
    email: support@zegocloud.com

servers:
  $ref: '../shared-components.yaml#/servers'

tags:
  - group

paths:
  /:
    post:
      tags: [group]
      summary: CreateGroup
      description: |
        By calling this API, you can create a group.

        After successful group creation, through the following ZIM SDK callback interfaces, the group owner will receive a notification of successful group creation, and other group members will receive a notification of joining the group:

        | iOS-25% | Android-25% | macOS-25% | Windows-25% |
        |----|----|----|----|
        | [groupStateChanged](/zim-ios/client-sdks/api-reference/protocol#zimgroupstatechangedeventoperatedinfogroupinfo-zimeventhandler) | [onGroupStateChanged](/zim-android/client-sdks/api-reference/class#ongroupstatechanged-zimeventhandler) | [groupStateChanged](/zim-macos/client-sdks/api-reference/protocol#zimgroupstatechangedeventoperatedinfogroupinfo-zimeventhandler) | [onGroupStateChanged](/zim-win/client-sdks/api-reference/class#ongroupstatechanged-zimeventhandler) |

        | Web-25% | Flutter-25% | React Native-25% |
        |----|----|----|
        | [onGroupStateChanged](/zim-web/client-sdks/api-reference/class#ongroupstatechanged-zimeventhandler) | [onGroupStateChanged](/zim-flutter/client-sdks/api-reference/class#ongroupstatechanged-zimeventhandler) | [onGroupStateChanged](/zim-rn/client-sdks/api-reference/class#ongroupstatechanged-zimeventhandler) |

        <Note title="Note">
        The users corresponding to the parameters `GroupOwner` and `UserId` have logged in to the ZIM service by calling the `login` method on the client, or the developer has registered the relevant userID by calling the [server-side API](/zim-server/user/batch-register-users).
        </Note>

        <Note title="Note">The parameters GroupId and GroupOwner only support numbers, English characters, and `'!','#','$','%','&','(',')','+','\'',':',';','<','=','.','>','?','@',
        '[',']','^','_','{','}','|','~'`.</Note>

        <Note title="QPS Limit"> 20 times/s</Note>
      operationId: create-a-group
      parameters:
        - name: Action
          in: query
          description: |
            > API prototype parameter
            >
            > https://zim-api.zego.im/?Action=CreateGroup
          required: true
          schema:
            type: string
            enum: [CreateGroup]
          style: form
          explode: true
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGroupRequest'
            example:
              GroupId: "group"
              GroupName: "group_name"
              GroupNotice: "group_notice"
              GroupAvatar: "https://www.baidu.com/"
              GroupOwner: "owner"
              UserId: ["user1", "user2"]
              Attributes:
                - Key: "key1"
                  Value: "value1"
                - Key: "key2"
                  Value: "value2"
              CreateGroupTime: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGroupResponse'
              example:
                  Code: 0
                  Message: success
                  RequestId: "343649807833778782"
                  GroupId: "group"
                  Members:
                    - UserId: "owner"
                      UserName: "owner"
                    - UserId: "user1"
                      UserName: "user1"
                  ErrorUsers:
                    - UserId: "user2"
                      SubCode: 660000015

components:
  schemas:
    CreateGroupRequest:
      type: object
      required: [GroupOwner]
      properties:
        GroupId:
          type: string
          description: Group ID, the unique identifier of the group, cannot start with "#". The maximum length is 32 bytes. If empty, it will be created by the ZIM server and defined with a "#" prefix.
          maxLength: 32
          example: "group"
        GroupName:
          type: string
          description: Group name. The maximum length is 50 characters. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
          maxLength: 50
          example: "group_name"
        GroupNotice:
          type: string
          description: Group notice. The maximum length is 300 bytes. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
          maxLength: 300
          example: "group_notice"
        GroupAvatar:
          type: string
          description: Group avatar URL. The maximum length is 500 bytes. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
          maxLength: 500
          example: "https://www.baidu.com/"
        GroupOwner:
          type: string
          description: User ID of the group owner. The maximum length is 32 bytes. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
          maxLength: 32
          example: "owner"
        UserId:
          type: array
          description: |
            IDs of users who need to join the group. The maximum length of each user ID is 32 bytes. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
            > **Note**
            >
            > - This array does not need to include the group owner. If the group owner is included, the ZIM server will automatically deduplicate.
            > - The join time of users in this array equals the group creation time, i.e., CreateGroupTime.
          maxItems: 100
          items:
            type: string
        Attributes:
          type: array
          description: Group attributes. The maximum number of group attributes is 10. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
          items:
            type: object
            required: [Key, Value]
            properties:
              Key:
                type: string
                description: Key of the group attribute. The maximum length is 16 bytes. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
                example: "key1"
              Value:
                type: string
                description: Value of the group attribute. The maximum length is 1024 bytes. If you need to adjust this limit, please contact ZEGOCLOUD Technical Support.
                example: "value1"
        CreateGroupTime:
          type: number
          description: |
            Timestamp for creating the group (in milliseconds).
            - If 0 or not filled: The group is created at the current time by default.
            - If other value: Cannot be greater than the current timestamp.
          example: 0
    CreateGroupResponse:
      type: object
      properties:
        Code:
          type: number
          description: |
            Return code.

            The following only lists the Code and SubCode related to the API business logic. For the complete return codes, please refer to [Return codes](/zim-server/return-codes).
            <table>
            <thead><tr><th>Code / SubCode</th><th>Description</th><th>Suggested Solution</th></tr></thead>
            <tbody>
            <tr><td>660000002</td><td>Parameter error.</td><td>Please check the request parameters.</td></tr>
            <tr><td>660600010</td><td>API call frequency limit exceeded.</td><td>Please try again later.</td></tr>
            <tr><td>660600011</td><td>Group already exists.</td><td>Please use another GroupId.</td></tr>
            <tr><td>660600012</td><td>Number of groups exceeds the limit.</td><td>Please upgrade your plan.</td></tr>
            <tr><td>660600013</td><td>Group owner does not exist.</td><td>Please check if the group owner ID is correct.</td></tr>
            <tr><td>660600014</td><td>Error modifying the group owner's group list.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660600015</td><td>ZIM server encountered an error executing db operation.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660600016</td><td>Number of group members exceeds the limit.</td><td>Please reduce the number of group members.</td></tr>
            <tr><td>660600017</td><td>User failed to join the group during group creation.</td><td>Please contact ZEGOCLOUD Technical Support.</td></tr>
            <tr><td>660600019</td><td>Number of attributes exceeds the limit.</td><td>Maximum of 10 by default.</td></tr>
            <tr><td>660600020</td><td>Attribute Key or Value length error.</td><td>Please check the length.</td></tr>
            </tbody>
            </table>
          example: 0
        Message:
          type: string
          description: Description of the operation result.
          example: "success"
        RequestId:
          type: string
          description: Request ID.
          example: "343649807833778782"
        GroupId:
          type: string
          description: Group ID.
        Members:
          type: array
          description: Information of users who successfully joined the group.
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Group user ID.
                example: "owner"
              UserName:
                type: string
                description: Group user name.
                example: "owner"
        ErrorUsers:
          type: array
          description: |
            Information of users who failed to join the group.
            <ul>
            <li>When Code is 0:</li>
            <li> If ErrorList is empty, all specified users successfully joined the group.</li>
            <li> If ErrorList is not empty, it means some specified users failed to join the group. Please refer to SubCode for handling.</li>
            </ul>
            <ul>
            <li>When Code is not 0:</li>
            <li>If ErrorList is empty, it indicates parameter error, API frequency limit, or system error.</li>
            <li>If ErrorList is not empty, it means all specified users failed to join the group.</li>
            </ul>
          items:
            type: object
            properties:
              UserId:
                type: string
                description: Failed user ID.
                example: "user2"
              SubCode:
                type: number
                description: |
                  Specific return code for user's failure to join the group. For the complete return codes, please refer to the Code description or [Return codes](/zim-server/return-codes).
                example: 660000015