openapi: 3.0.0
info:
  title: open-api-desc
  version: 1.0.0
  contact:
    name: AI Agent API Support
    email: support@zegocloud.com

servers:
  - url: https://aigc-aiagent-api.zegotech.cn
    description: 统一接入地址（不区分区域）
  - url: https://aigc-aiagent-api-sha.zegotech.cn
    description: 中国大陆（上海）

tags:
  - name: agent-instance-management

paths:
  /:
    post:
      tags:
        - agent-instance-management
      summary: CreateLiveDigitalHumanAgentInstance
      description: |
        通过本接口，您可以创建播报数字人智能体实例，并将智能体实例加入到语音（RTC）对话之中，或将画面推流到第三方平台（如 Facebook、TikTok 等）。

        <Warning title="注意">
        - 默认情况下一个账号下最多同时存在 10 个数字人智能体实例，超过限制后创建数字人智能体实例会失败，如需调整请联系 ZEGO 商务。
        </Warning>
      operationId: create-live-digital-human-agent-instance
      parameters:
        - name: Action
          in: query
          description: |
            > 接口原型参数
            >
            > https://aigc-aiagent-api.zegotech.cn?Action=CreateLiveDigitalHumanAgentInstance
          required: true
          allowEmptyValue: false
          schema:
            type: string
            enum: [CreateLiveDigitalHumanAgentInstance]
          style: form
          explode: true
        # 引用共享的参数
        - $ref: '../shared-components.yaml#/components/parameters/AppId'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureNonce'
        - $ref: '../shared-components.yaml#/components/parameters/Timestamp'
        - $ref: '../shared-components.yaml#/components/parameters/Signature'
        - $ref: '../shared-components.yaml#/components/parameters/SignatureVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLiveDigitalHumanAgentInstanceRequest"
            example:
              AgentId: "xiaozhi"
              RTC:
                RoomId: "room_1"
                AgentStreamId: "agent_stream_1"
                AgentUserId: "agent_user_1"
              DigitalHuman:
                DigitalHumanId: "xiaozhi"
                ConfigId: "mobile"
                EncodeCode: "H264"
      responses:
        "200":
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateLiveDigitalHumanAgentInstanceResponse"

components:
  schemas:
    CreateLiveDigitalHumanAgentInstanceRequest:
      type: object
      required:
        - AgentId
        - DigitalHuman
      properties:
        AgentId:
          type: string
          description: 已注册的智能体唯一标识符
          example: "xiaozhi"
        RTC:
          $ref: '#/components/schemas/RTC_Live'
        CDN:
          $ref: '#/components/schemas/CDN'
        TTS:
          $ref: '../shared-components.yaml#/components/schemas/TTS'
        CallbackConfig:
          $ref: '#/components/schemas/CallbackConfig_Live'
        AdvancedConfig:
          $ref: '#/components/schemas/AdvancedConfig_Live'
        DigitalHuman:
          $ref: '../shared-components.yaml#/components/schemas/DigitalHuman'

    CreateLiveDigitalHumanAgentInstanceResponse:
      type: object
      properties:
        Code:
          type: integer
          description: 返回码，0 表示成功，其他值表示失败。详情请参考 [返回码](/aiagent-server/api-reference/return-codes) 说明。
          example: 0
        Message:
          type: string
          description: 请求结果说明
          example: "success"
        RequestId:
          type: string
          description: 请求 ID
          example: "3151527792559699732"
        Data:
          type: object
          properties:
            AgentInstanceId:
              type: string
              description: 智能体实例的唯一标识。
              example: "1912122918452641792"
            DigitalHumanConfig:
              type: string
              description: 数字人配置，给数字人移动端 SDK 使用。
              example: "eyJEaWdpdGFsSHVtYW5JZCI6ImU1ODNkMzVmLTk3OTMtNDJiNC1hYjFiLTE4OWEzNWI4OGQxYyIsIlN0cmVhbXMiOlt7IlJvb21JZCI6ImlyXzU1NTd5bDVoIiwiU3RyZWFtSWQiOiJpcl81NTU3eWw1aF8xNzEwMl9hZ2VudCIsIkVuY29kZUNvZGUiOiJIMjY0IiwiQ29uZmlnSWQiOiJ3ZWIifV19"

    CDN:
      type: object
      description: |
        CDN 推流配置。

        <Note type="info">
        RTC 与 CDN 配置二选一。如果两个都设置，以 CDN 为准。
        </Note>
      required:
        - Url
      properties:
        Url:
          type: string
          description: CDN 推流地址。
          example: "rtmp://push.example.com/live/stream_key"

    CallbackConfig_Live:
      type: object
      description: |
        服务端回调配置（播报数字人场景）

        <div>
        <br/>
        <strong>📌 重要说明</strong>
        <p>在配置以下参数前，你需要参考 [接收回调](/aiagent-server/callbacks/receiving-callback) 设置好回调地址，并了解具体字段说明。</p>
        </div>

      properties:
        Interrupted:
          type: integer
          description: 是否开启服务端回调智能体被打断结果。
          enum: [0, 1]
          default: 0
        AgentInstanceStatus:
          type: integer
          description: 是否开启服务端回调智能体实例状态的回调。
          enum: [0, 1]
          default: 0
        HostTag:
          type: string
          description: |
            可以设置最多两个回调地址用于监听用户与智能体对话过程中所发生的事件。通过该参数指定该实例的事件回调到哪个地址。具体 tag 值需联系 ZEGO 技术支持预先配置好。
          example: "Custom1"

    RTC_Live:
      type: object
      description: |
        <div>
          <p>RTC 相关信息（播报数字人场景）</p>
        </div>

        <Note type="info">
        - 所有属性字符限制：仅支持数字、英文字符、'_'、'-'、'.'<br/>- 播报数字人场景下不需要 `UserStreamId`<br/>- RTC 与 CDN 配置二选一。如果两个都设置，以 CDN 为准
        </Note>
      required:
        - RoomId
        - AgentStreamId
        - AgentUserId
      properties:
        RoomId:
          type: string
          description: RTC 房间 ID。
          maxLength: 128
          example: "room_1"
        AgentStreamId:
          type: string
          description: |
            智能体实例推流使用的流 ID。
            > **📌 重要说明**
            >
            > 请确保当前运行中的多个智能体实例（即便不在同一个 RTC 房间）使用不同的流 ID，否则会导致后创建的智能体实例推流失败。
          maxLength: 128
          example: "agent_stream_1"
        AgentUserId:
          type: string
          description: |
            智能体实例的用户 ID。
            > **📌 重要说明**
            >
            > 需确保同时在运行中的多个智能体实例（即便不在同一个 RTC 房间）使用不同的用户 ID，否则先创建的智能体实例会被踢出 RTC 房间。
          maxLength: 32
          example: "agent_user_1"
        StreamExtraInfo:
          type: string
          description: |
            Agent 推流时设置的流附加信息，长度不超过1024字节的字符串。客户端可以通过 [onRoomStreamExtraInfoUpdate](/real-time-video-android-java/client-sdk/api/class/izegoeventhandler#onroomstreamextrainfoupdate-izegoeventhandler-class) 回调监听。
          maxLength: 1024
          example: "extra_info_data"

    AdvancedConfig_Live:
      type: object
      description: |
        高级配置（播报数字人场景）。
      properties:
        MaxIdleTime:
          type: integer
          description: |
            智能体实例的自动销毁时间。数字人最大空闲时长，持续达到该时间未调用 [SendAgentInstanceTTS](/aiagent-server/api-reference/agent-instance-control/send-agent-instance-tts) 接口驱动数字人，任务将自动结束。单位为秒，取值范围 [30, 86400]，默认值为 900 秒（15 分钟）。
          minimum: 30
          maximum: 86400
          default: 900
          example: 900
        DisableTTS:
          type: boolean
          description: |
            是否禁用 TTS 功能。如果设置为 true，则智能体实例不会进行语音合成。
            > **📌 重要说明**
            >
            > DisableTTS 为 true 时，调用[创建播报数字人智能体实例](/aiagent-server/api-reference/agent-instance-management/create-live-digital-human-agent-instance)及[主动调用 TTS](/aiagent-server/api-reference/agent-instance-control/send-agent-instance-tts)接口都会报错。
          default: false
          example: false
        TTSParamPaths:
          type: object
          description: |
            TTS 各家厂商可以通过一些参数控制合成的语音情绪效果。这个参数控制 LLM 输出内容中如何通过元数据标志映射为 TTS 情绪控制参数。该参数可以设置多个 string 类型的键值对。<br/><br/>

            比如：`"TTSParamPaths": {"instruction": "payload.parameters.instruction"}`<br/><br/>

            表示 LLM 输出为 `[[{"instruction":"用温柔的语气"}]]你好` 时，会将这段输出中的元数据 `{"instruction":"用温柔的语气"}` 的 `instruction` 对应的值 `用温柔的语气` 提取出来，作为值传给 TTS 厂商接口的 `payload.parameters.instruction` 参数。<br/>

            TTSParamPaths 的 key 可以根据业务逻辑自定义（例如将 `instruction` 换成 `i`），只需保证 LLM 输出的元数据 key 与 TTSParamPaths 中定义的 key 一致即可。
          additionalProperties:
            type: string
          example:
            instruction: "payload.parameters.instruction"
            context_texts: "req_params.additions.context_texts"
            pitch: "req_params.additions.post_process.pitch"
